### ISSUE TITLE
Avira reports SPR/ANDR.SMSreg.GE.Gen has been detected in Atomic

### ISSUE THREAD

**Issue by mark-orion** [indrora/Atomic#105]
Avira for Android reports Atomic as a "potentially unwanted application":
indrora.atomic-1.apk
SPR/ANDR.SMSreg.GE.Gen has been detected

I am not sure if this is just a false positive on Avira, but I better report it here.

**Comment by indrora** [comment]
Another day, another AV says I'm trying to ~~pwn some gibsons~~ use old APIs for fallbacks.

**Comment by Mr-Kumar-Abhishek** [comment]
:laughing:  This is in yaaic too, it makes sense that it cropped up here too.

**Comment by indrora** [comment]
Yet another year, another AV says I'm trying to ~~make crappy phone calls from people's butts~~ use old APIs for callbacks.
