### ISSUE TITLE
Server password

### ISSUE THREAD

**Issue by WyRe** [indrora/Atomic#121]
I would like to know if is there a way to auth using server password in the network settings, since I only can identify through Nickserv or SASL, I'm using a ZNC bouncer what requieres an auth like /quote PASS <user>:<pass>

If I put that command between init commands doesn't work either. Ty so much :D

**Comment by indrora** [comment]
[Did you read the documentation?](https://github.com/indrora/Atomic/wiki/Bouncer-configuration)

**Comment by WyRe** [comment]
Oh, Thanks, I'm so sorry :S ...

**Comment by indrora** [comment]
There actually needs to be a link in the app that takes you to the docs.
