### ISSUE TITLE
ZNC

### ISSUE THREAD

**Issue by ranyyy** [indrora/Atomic#127]
Could you please add ZNC support?

**Comment by cebe** [comment]
can you elaborate about what needs to be added for this to work? Why can't you use it currently?

**Comment by ranyyy** [comment]
It doesn't playback anything.

**Comment by ranyyy** [comment]
I tried using HoloIRC and it did playback everything correctly.

**Comment by Brottweiler** [comment]
I use ZNC with this just fine. 

>It doesn't playback anything.

So you mean everything works fine, just you get no buffer from when you were detached?

**Comment by ranyyy** [comment]
Yes

**Comment by Brottweiler** [comment]
You won't get buffer if you are attached somewhere else. I just attached now from being detached for several hours, and I get playback buffer.

**Comment by ranyyy** [comment]
Strange...it works fine with HoloIRC. I also requested this in YAAIC and the dev just tagged it as a feature. So I think this hasn't yet been implemented in the app.

**Comment by indrora** [comment]
ZNC is supported. If you aren't getting content, it's because you have the auto buffer-clearing turned on.
