### ISSUE TITLE
Highlights don't trigger a standard notification

### ISSUE THREAD

**Issue by LuccoJ** [indrora/Atomic#57]
While the response to highlight is almost fully configurable (sound, vibration and LED independently, plus the highlighting message in the notification bar), and thus can imitate a notification's behavior, it is not an actual notification in the standard Android sense.
This has as a consequence that other programs meant to catch notifications for various purpose (waking up the phone aka "Active Display"; reading notifications alout with TTS; remotely execute actions; etc) cannot hook into Atomic's highlights.
More over, the "non-notification" with the message's text cannot be swiped away (because it's a permanent notification), meaning that to stop the LED from blinking, one has to tap on it and bring up Atomic's foreground activity, which is needlessly disruptive for notifications one wishes to discard.

I suggest that the present mechanism not be removed, as people might still find the ad-hoc configurability convenient (on Android flavors that don't allow configuring notification behavior per-app), but instead that a standard notification be added as an runtime configurable alternative.

**Comment by indrora** [comment]
The notification is now a low-priority notification (meaning Active Display shouldn't pick it up) until it's not (then it becomes a high priority)
