### ISSUE TITLE
Let user to disable/remove Atomic icon from status menu(Android top)

### ISSUE THREAD

**Issue by atomix2** [indrora/Atomic#69]
Atomic icon is always there.
I want to keep status bar clean. Please add an option to disable Atomic icon completely.

I want to be notified ONLY if
1. someone chat directly to me. (PRIVMSG)
2. Atomic is not opened in front. (e.g. I'm using other application)

**Comment by indrora** [comment]
... A year later, I'll come back to this:

No. It's now low priority, at least. It's also a vague requirement for being a "foreground" service.
