### ISSUE TITLE
[Feature Request] Allow Export/Import of config files

### ISSUE THREAD

**Issue by benoliver999** [indrora/Atomic#86]
This would be great for people:

1. On multiple devices
2. Who would like to edit manually

The latter applies to ZNC users who connect to lots of networks. The 'password' is elaborate (username/network:zncpass) and hard to edit by simply duplicating settings and changing it. However, with a text editor this task would be a breeze since the field only has one variable for every network - it's just awkward to deal with on the phone.

Perhaps an initial step would be to enable a 'show password' field? This would solve the latter problem but probably isn't as universally handy as an import/export feature.

**Comment by indrora** [comment]
Since you mention znc, try using 'username/network' in the user/ident
field.

**Comment by benoliver999** [comment]
Sorry, I don't quite catch your drift. This is what I see on the add server screen:

![atomic1](https://s3.amazonaws.com/pushbullet-uploads/ujyycvvlf2a-HWfqZ6fddTqrp1h1rDBcOqBltXFUA4Ev/Screenshot_2015-02-20-09-08-35.png)

![atomic2](https://s3.amazonaws.com/pushbullet-uploads/ujyycvvlf2a-HWfqZ6fddTqrp1h1rDBcOqBltXFUA4Ev/Screenshot_2015-02-20-09-08-35.png)

Sorry for the huge pictures, I'm on my mobile...!

**Comment by indrora** [comment]
ZNC Configuration does not require gigantic passwords: https://github.com/indrora/Atomic/wiki/Bouncer-configuration

As for import/export of configurations? It's coming.

**Comment by benoliver999** [comment]
Ah - I get it! Thank you, works great. For some reason I've always passed the whole set of details as the password.

**Comment by indrora** [comment]
It's a common thing. I'll be adding an "Add Server" wizard some time soon.
