### ISSUE TITLE
Issues with promoting users, no halfop support.

### ISSUE THREAD

**Issue by toadfan321** [indrora/Atomic#87]
Been noticing that i cant promote users through the userlist or just by doing /op, im not sure if this has to do woth the use of a bouncer or what, but its worked fine on other clients so im not sure whats going wrong. Also i noticed a severe lack of support for halfop, whenever someone is halfopped the message doesnt appear for me untill i reconnect to mu bouncer, and the same goes for them showing as halfopped in the user list, theres also not an option to promote someone to halfop. Just another couple bugs ive noticed, but otherwise this is still my favorite client.

**Comment by paytonq** [comment]
@indrora Do you want to close this?

**Comment by toadfan321** [comment]
Thanks for fixing this!

**Comment by paytonq** [comment]
No problem!
